### ISSUE TITLE
Parallax v3.0 not working on the latest IE11

### ISSUE THREAD

**Issue by pingshunhuangalex** [wagerfield/parallax#202]
Hi @wagerfield 
I just found out about your amazing plugin today. When I'm testing the latest Parallax v3.0 in IE, it doesn't work at, but it works pretty well in Chrome.

I'm using the latest IE11 in Win10, so it shouldn't be considered an "old" IE, just wonder if there's anything you can do to fix it. Thanks.

**Comment by RRorg** [comment]
hey @pingshunhuangalex - I am to blame for this :( @wagerfield s old version should work with IE, if there's an incompatibility in the v3, it's caused by me. Of course I will try fixing this later today, as soon as I'm done with my day job!

**Comment by pingshunhuangalex** [comment]
No problem @RRorg, take as much time as you need. Great work on the plug-in and save me a ton of time.

Instead of opening a new issue, I'll just briefly mention it here cuz this request may be too much. Since now we have a brand new v3.0, do you think realising 3D parallax like [this](http://www.vermont.eu/en/about) would be something on your list? Thanks.

**Comment by RRorg** [comment]
I've fixed this in commit #e74e821 , the culprit was `Object.assign` being unavailable on older Internet Explorer versions, it's now being polyfilled.

I see the requests for 3D Parallax, but at that point, it could be too much to implement in this version. But I've thought about modularizing the Parallax framework, too. As it is now, it could be split up into two very distinct packages - one to detect the form of input, attach the event handlers, and sanitize the inputs, the second to use those input numbers and generate the parallax view from it.  
One approach would be to isolate the input-part and provide hooks for custom output-modules.

I'll close this issue, since the original bug should be solved now. Feel free to open another issue if you want to share further ideas or anything else isn't working the way it should! 🙂

**Comment by pingshunhuangalex** [comment]
Hi @RRorg 
I just tested it out. Unfortunately, it's still not working in IE11.

Just to make sure I did everything right:
1. I downloaded the repository master
2. I ran `npm i` in the repository folder
3. I grabbed the minified js in ths `dist` folder

**Comment by RRorg** [comment]
Can you provide me with the error log you get in IE11? I probably missed something :( sorry about that!

**Comment by pingshunhuangalex** [comment]
No worries @RRorg 
Here is the problem, there is actually no error displayed in IE... Since it works in Chrome, it has to have something to do with the modern ES6 JS I assume. Do you have IE on your side you can test with?

**Comment by RRorg** [comment]
I've tested it on my desktop computer with IE11 - maybe the input type detection is flakey?  
ES6 is compiled by babel to Internet-Explorer-compatible traditional Javascript, that should not be the culprit.

Please test with the provided demos (clone repo, run `npm install` and `gulp watch`):
- is the parallax correctly accessing the elements, as in, do they have their styles set?
- what values are you getting for the attributes `desktop`, `motionSupport`, `motionStatus`, `orientationSupport` and `orientationStatus` of the parallax instance? Maybe the device you're using is wrongfully reporting motion support?

**Comment by pingshunhuangalex** [comment]
Hi @RRorg 
I think you may be right about input type.

To rule out any code issue on my end (not likely), I tested everything using the examples in the repository. Similarly, they all work in Chrome but not in IE 11. Both browsers can recognise `parallax` without any issues, but yield very different results for the attributes you requested.

```
**Chrome** (working)
parallax.desktop = true,
parallax.motionSupport = false,
parallax.motionStatus = 0,
parallax.orientationSupport = false,
parallax.orientationStatus = 0
```
```
**IE11** (not working)
parallax.desktop = false,
parallax.motionSupport = true,
parallax.motionStatus = 0,
parallax.orientationSupport = false,
parallax.orientationStatus = 0
```

I do use a Lenovo laptop with touch screen (not splittable). It's never been an issue before, so I didn't even think in that direction, but this could be the case. Thanks.

**Comment by RRorg** [comment]
I think I've got an idea - what is the output for `navigator.userAgent`?

IE11 provides many different user agents, based on software and hardware configuration. This is why they suggest using feature detection instead of user agent sniffing - but as we can see from our problem here, feature detection is not reliable, since they're returning motion support even without motion hardware. I wonder why the event even gets fired in your case? Thanks, Microsoft!

**Comment by pingshunhuangalex** [comment]
Well, laptops that accept both touch inputs and mouse inputs can always be confusing for the system, especially for IE, including their own Surface. Just nightmare for frontend.

```
Chrome 59 (working)
navigator.userAgent
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
```
```
IE 11 (not working)
navigator.userAgent
"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; rv:11.0) like Gecko"
```

**Comment by RRorg** [comment]
Finally got it fixed (I hope!)
https://github.com/wagerfield/parallax/commit/946051fd68979c11372adf572df55eaf337881b7
Please let me know if it works now :)

**Comment by pingshunhuangalex** [comment]
@RRorg It works like a charm. Thanks so much!
